global:
  scrape_interval: 15s
  scrape_timeout: 10s
  external_labels:
    env: dev
    app: student-management

scrape_configs:
  - job_name: student-management
    metrics_path: /api/actuator/prometheus
    static_configs:
      - targets: ['host.docker.internal:8080']
        labels:
          instance: backend-dev
