-- V26.3.0 (OBSOLETE / NO-OP)
--
-- 历史意图: 为所有教学任务分配教师 (seed 数据), 通过
--   `SELECT id FROM users WHERE primary_org_unit_id = <dept> AND user_type_code='TEACHER'`
--   按系部挑教师填 teaching_task_teachers。
--
-- 现已作废: 组织归属唯一真相源统一为 access_relations 的 member 关系
--   (V20260531_4 已删 users.primary_org_unit_id 列)。该迁移的全部子查询都依赖已删列,
--   且是一次性 demo 种子数据 (开发期无需保留)。整体改为 no-op;
--   如需教师任务分配演示数据, 改由按 member 关系挑选的 seed 脚本承载。
SELECT 'V26.3.0 obsolete: teacher assignment seed depended on dropped primary_org_unit_id' AS msg;
