tinymce.addI18n('zh_CN', {
  "Redo": "重做",
  "Undo": "撤销",
  "Cut": "剪切",
  "Copy": "复制",
  "Paste": "粘贴",
  "Select all": "全选",
  "New document": "新建文档",
  "Ok": "确定",
  "Cancel": "取消",
  "Visual aids": "视觉辅助",
  "Bold": "粗体",
  "Italic": "斜体",
  "Underline": "下划线",
  "Strikethrough": "删除线",
  "Superscript": "上标",
  "Subscript": "下标",
  "Clear formatting": "清除格式",
  "Remove": "移除",
  "Align left": "左对齐",
  "Align center": "居中对齐",
  "Align right": "右对齐",
  "No alignment": "无对齐",
  "Justify": "两端对齐",
  "Bullet list": "项目符号列表",
  "Numbered list": "编号列表",
  "Decrease indent": "减少缩进",
  "Increase indent": "增加缩进",
  "Close": "关闭",
  "Formats": "格式",
  "Your browser doesn't support direct access to the clipboard. Please use the Ctrl+X/C/V keyboard shortcuts instead.": "您的浏览器不支持直接访问剪贴板，请使用Ctrl+X/C/V快捷键。",
  "Headings": "标题",
  "Heading 1": "标题 1",
  "Heading 2": "标题 2",
  "Heading 3": "标题 3",
  "Heading 4": "标题 4",
  "Heading 5": "标题 5",
  "Heading 6": "标题 6",
  "Preformatted": "预格式化",
  "Div": "Div",
  "Pre": "预格式文本",
  "Code": "代码",
  "Paragraph": "段落",
  "Blockquote": "引用",
  "Inline": "行内",
  "Blocks": "块",
  "Paste is now in plain text mode. Contents will now be pasted as plain text until you toggle this option off.": "当前为纯文本粘贴模式，直到你取消此选项。",
  "Fonts": "字体",
  "Font sizes": "字号",
  "Class": "类",
  "Browse for an image": "浏览图片",
  "OR": "或",
  "Drop an image here": "拖放图片到此处",
  "Upload": "上传",
  "Uploading image": "上传图片中",
  "Block": "块",
  "Align": "对齐",
  "Default": "默认",
  "Circle": "圆圈",
  "Disc": "实心圆",
  "Square": "方块",
  "Lower Alpha": "小写字母",
  "Lower Greek": "小写希腊字母",
  "Lower Roman": "小写罗马数字",
  "Upper Alpha": "大写字母",
  "Upper Roman": "大写罗马数字",
  "Anchor...": "锚点...",
  "Anchor": "锚点",
  "Name": "名称",
  "ID": "ID",
  "ID should start with a letter, followed only by letters, numbers, dashes, dots, colons or underscores.": "ID应以字母开头，后跟字母、数字、破折号、点、冒号或下划线。",
  "You have unsaved changes are you sure you want to navigate away?": "您有未保存的更改，确定要离开吗？",
  "Restore last draft": "恢复上次草稿",
  "Special character...": "特殊字符...",
  "Special Character": "特殊字符",
  "Source code": "源代码",
  "Insert/Edit code sample": "插入/编辑代码示例",
  "Language": "语言",
  "Code sample...": "代码示例...",
  "Left to right": "从左到右",
  "Right to left": "从右到左",
  "Title": "标题",
  "Fullscreen": "全屏",
  "Action": "操作",
  "Shortcut": "快捷键",
  "Help": "帮助",
  "Address": "地址",
  "Focus to menubar": "聚焦到菜单栏",
  "Focus to toolbar": "聚焦到工具栏",
  "Focus to element path": "聚焦到元素路径",
  "Focus to contextual toolbar": "聚焦到上下文工具栏",
  "Insert link (if link plugin activated)": "插入链接（如果链接插件已激活）",
  "Save (if save plugin activated)": "保存（如果保存插件已激活）",
  "Find (if searchreplace plugin activated)": "查找（如果查找替换插件已激活）",
  "Plugins installed ({0}):": "已安装插件 ({0}):",
  "Premium plugins:": "高级插件:",
  "Learn more...": "了解更多...",
  "You are using {0}": "您正在使用 {0}",
  "Plugins": "插件",
  "Handy Shortcuts": "快捷键",
  "Horizontal line": "水平线",
  "Insert/edit image": "插入/编辑图片",
  "Alternative description": "替代描述",
  "Accessibility": "可访问性",
  "Image is decorative": "图片是装饰性的",
  "Source": "源",
  "Dimensions": "尺寸",
  "Constrain proportions": "保持比例",
  "General": "常规",
  "Advanced": "高级",
  "Style": "样式",
  "Vertical space": "垂直间距",
  "Horizontal space": "水平间距",
  "Border": "边框",
  "Insert image": "插入图片",
  "Image...": "图片...",
  "Image list": "图片列表",
  "Resize": "调整大小",
  "Insert date/time": "插入日期/时间",
  "Date/time": "日期/时间",
  "Insert/edit link": "插入/编辑链接",
  "Text to display": "显示文本",
  "Url": "链接",
  "Open link in...": "在...中打开链接",
  "Current window": "当前窗口",
  "None": "无",
  "New window": "新窗口",
  "Open link": "打开链接",
  "Remove link": "移除链接",
  "Anchors": "锚点",
  "Link...": "链接...",
  "Paste or type a link": "粘贴或输入链接",
  "The URL you entered seems to be an email address. Do you want to add the required mailto: prefix?": "您输入的URL似乎是电子邮件地址，是否添加mailto:前缀？",
  "The URL you entered seems to be an external link. Do you want to add the required http:// prefix?": "您输入的URL似乎是外部链接，是否添加http://前缀？",
  "The URL you entered seems to be an external link. Do you want to add the required https:// prefix?": "您输入的URL似乎是外部链接，是否添加https://前缀？",
  "Link list": "链接列表",
  "Insert video": "插入视频",
  "Insert/edit video": "插入/编辑视频",
  "Insert/edit media": "插入/编辑媒体",
  "Alternative source": "替代来源",
  "Alternative source URL": "替代来源URL",
  "Media poster (Image URL)": "媒体封面（图片URL）",
  "Paste your embed code below:": "在下方粘贴嵌入代码：",
  "Embed": "嵌入",
  "Media...": "媒体...",
  "Nonbreaking space": "不换行空格",
  "Page break": "分页符",
  "Paste as text": "粘贴为文本",
  "Preview": "预览",
  "Print": "打印",
  "Print...": "打印...",
  "Save": "保存",
  "Find": "查找",
  "Replace with": "替换为",
  "Replace": "替换",
  "Replace all": "全部替换",
  "Previous": "上一个",
  "Next": "下一个",
  "Find and Replace": "查找和替换",
  "Find and replace...": "查找和替换...",
  "Could not find the specified string.": "未找到指定字符串。",
  "Match case": "区分大小写",
  "Find whole words only": "仅查找整个单词",
  "Find in selection": "在选区中查找",
  "Insert table": "插入表格",
  "Table properties": "表格属性",
  "Delete table": "删除表格",
  "Cell": "单元格",
  "Row": "行",
  "Column": "列",
  "Cell properties": "单元格属性",
  "Merge cells": "合并单元格",
  "Split cell": "拆分单元格",
  "Insert row before": "在上方插入行",
  "Insert row after": "在下方插入行",
  "Delete row": "删除行",
  "Row properties": "行属性",
  "Cut row": "剪切行",
  "Cut column": "剪切列",
  "Copy row": "复制行",
  "Copy column": "复制列",
  "Paste row before": "在上方粘贴行",
  "Paste column before": "在左侧粘贴列",
  "Paste row after": "在下方粘贴行",
  "Paste column after": "在右侧粘贴列",
  "Insert column before": "在左侧插入列",
  "Insert column after": "在右侧插入列",
  "Delete column": "删除列",
  "Cols": "列数",
  "Rows": "行数",
  "Width": "宽度",
  "Height": "高度",
  "Cell spacing": "单元格间距",
  "Cell padding": "单元格内边距",
  "Row clipboard actions": "行剪贴板操作",
  "Column clipboard actions": "列剪贴板操作",
  "Table styles": "表格样式",
  "Cell styles": "单元格样式",
  "Column header": "列标题",
  "Row header": "行标题",
  "Table caption": "表格标题",
  "Caption": "标题",
  "Show caption": "显示标题",
  "Left": "左",
  "Center": "居中",
  "Right": "右",
  "Cell type": "单元格类型",
  "Scope": "范围",
  "Alignment": "对齐",
  "Horizontal align": "水平对齐",
  "Vertical align": "垂直对齐",
  "Top": "顶部",
  "Middle": "中部",
  "Bottom": "底部",
  "Header cell": "表头单元格",
  "Row group": "行组",
  "Column group": "列组",
  "Row type": "行类型",
  "Header": "表头",
  "Body": "主体",
  "Footer": "页脚",
  "Border color": "边框颜色",
  "Solid": "实线",
  "Dotted": "点线",
  "Dashed": "虚线",
  "Double": "双线",
  "Groove": "凹槽",
  "Ridge": "脊线",
  "Inset": "内嵌",
  "Outset": "外凸",
  "Hidden": "隐藏",
  "Insert template...": "插入模板...",
  "Templates": "模板",
  "Template": "模板",
  "Insert Template": "插入模板",
  "Text color": "文本颜色",
  "Background color": "背景颜色",
  "Custom...": "自定义...",
  "Custom color": "自定义颜色",
  "No color": "无颜色",
  "Remove color": "移除颜色",
  "Show blocks": "显示块",
  "Show invisible characters": "显示不可见字符",
  "Word count": "字数统计",
  "Count": "计数",
  "Document": "文档",
  "Selection": "选区",
  "Words": "字词",
  "Words: {0}": "字词: {0}",
  "{0} words": "{0} 字词",
  "File": "文件",
  "Edit": "编辑",
  "Insert": "插入",
  "View": "查看",
  "Format": "格式",
  "Table": "表格",
  "Tools": "工具",
  "Powered by {0}": "由 {0} 提供支持",
  "Rich Text Area. Press ALT-F9 for menu. Press ALT-F10 for toolbar. Press ALT-0 for help": "富文本区域。按ALT-F9打开菜单，按ALT-F10打开工具栏，按ALT-0获取帮助",
  "Image title": "图片标题",
  "Border width": "边框宽度",
  "Border style": "边框样式",
  "Error": "错误",
  "Warn": "警告",
  "Valid": "有效",
  "To open the popup, press Shift+Enter": "按Shift+Enter打开弹出窗口",
  "Rich Text Area": "富文本区域",
  "Rich Text Area. Press ALT-0 for help.": "富文本区域。按ALT-0获取帮助。",
  "System Font": "系统字体",
  "Failed to upload image: {0}": "图片上传失败: {0}",
  "Failed to load plugin: {0} from url {1}": "加载插件失败: {0} 来自 {1}",
  "Failed to load plugin url: {0}": "加载插件URL失败: {0}",
  "Failed to initialize plugin: {0}": "初始化插件失败: {0}",
  "example": "示例",
  "Search": "搜索",
  "All": "全部",
  "Currency": "货币",
  "Text": "文本",
  "Quotations": "引号",
  "Mathematical": "数学",
  "Extended Latin": "扩展拉丁语",
  "Symbols": "符号",
  "Arrows": "箭头",
  "User Defined": "用户定义",
  "dollar sign": "美元符号",
  "currency sign": "货币符号",
  "euro-currency sign": "欧元符号",
  "colon sign": "冒号",
  "cruzeiro sign": "克鲁塞罗符号",
  "french franc sign": "法郎符号",
  "lira sign": "里拉符号",
  "mill sign": "密尔符号",
  "naira sign": "奈拉符号",
  "peseta sign": "比塞塔符号",
  "rupee sign": "卢比符号",
  "won sign": "韩元符号",
  "new sheqel sign": "新谢克尔符号",
  "dong sign": "越南盾符号",
  "kip sign": "基普符号",
  "tugrik sign": "图格里克符号",
  "drachma sign": "德拉克马符号",
  "german penny symbol": "德国芬尼符号",
  "peso sign": "比索符号",
  "guarani sign": "瓜拉尼符号",
  "austral sign": "澳元符号",
  "hryvnia sign": "格里夫纳符号",
  "cedi sign": "塞地符号",
  "livre tournois sign": "图尔里弗符号",
  "spesmilo sign": "斯佩斯米洛符号",
  "tenge sign": "坚戈符号",
  "indian rupee sign": "印度卢比符号",
  "turkish lira sign": "土耳其里拉符号",
  "nordic mark sign": "北欧马克符号",
  "manat sign": "马纳特符号",
  "ruble sign": "卢布符号",
  "yen character": "日元字符",
  "yuan character": "人民币字符",
  "yuan character, in hong kong and taiwan": "港台人民币字符",
  "yen/yuan character variant one": "日元/人民币字符变体一",
  "Emojis": "表情符号",
  "Emojis...": "表情符号...",
  "Loading emojis...": "加载表情符号...",
  "Could not load emojis": "无法加载表情符号",
  "People": "人物",
  "Animals and Nature": "动物和自然",
  "Food and Drink": "食物和饮料",
  "Activity": "活动",
  "Travel and Places": "旅行和地点",
  "Objects": "物品",
  "Flags": "旗帜",
  "Characters": "字符",
  "Characters (no spaces)": "字符（无空格）",
  "{0} characters": "{0} 个字符",
  "Error: Form submit field collision.": "错误：表单提交字段冲突。",
  "Error: No form element found.": "错误：未找到表单元素。",
  "Color swatch": "颜色样本",
  "Color Picker": "颜色选择器",
  "Invalid hex color code: {0}": "无效的十六进制颜色代码: {0}",
  "Invalid input": "无效输入",
  "R": "R",
  "G": "G",
  "B": "B",
  "Color value": "颜色值"
});
