-- =============================================================================
-- V112.0.0__reconcile_po_column_gaps.sql
-- Purpose: Reconcile MyBatis-Plus PO classes against the rebuilt MySQL schema.
--   The live DB was lost and rebuilt by replaying drifted migrations; some
--   tables ended up missing columns the application code (PO classes) expects.
--   PO classes are the source of truth. This script ADDs every column the app
--   reads/writes that the rebuilt DB currently lacks. All adds are NULLable
--   (safe for existing rows). Generated by column-level reconciliation.
-- =============================================================================
SET NAMES utf8mb4;

-- ### academic_weeks
ALTER TABLE `academic_weeks` ADD COLUMN `week_type` INT NULL COMMENT '1=教学 2=考试 3=假期';

-- ### data_resources
ALTER TABLE `data_resources` ADD COLUMN `access_resource_type` VARCHAR(255) NULL;

-- ### grades
ALTER TABLE `grades` ADD COLUMN `graduation_year` INT NULL;
ALTER TABLE `grades` ADD COLUMN `grade_director_id` BIGINT NULL;
ALTER TABLE `grades` ADD COLUMN `grade_counselor_id` BIGINT NULL;
ALTER TABLE `grades` ADD COLUMN `total_classes` INT NULL;
ALTER TABLE `grades` ADD COLUMN `total_students` INT NULL;
ALTER TABLE `grades` ADD COLUMN `standard_class_size` INT NULL;
ALTER TABLE `grades` ADD COLUMN `remarks` TEXT NULL;

-- ### insp_corrective_cases
ALTER TABLE `insp_corrective_cases` ADD COLUMN `issue_category_id` BIGINT NULL;
ALTER TABLE `insp_corrective_cases` ADD COLUMN `deficiency_code` VARCHAR(255) NULL;
ALTER TABLE `insp_corrective_cases` ADD COLUMN `rca_method` VARCHAR(255) NULL;
ALTER TABLE `insp_corrective_cases` ADD COLUMN `rca_data` VARCHAR(255) NULL;
ALTER TABLE `insp_corrective_cases` ADD COLUMN `preventive_action` VARCHAR(255) NULL;
ALTER TABLE `insp_corrective_cases` ADD COLUMN `effectiveness_status` VARCHAR(255) NULL;
ALTER TABLE `insp_corrective_cases` ADD COLUMN `effectiveness_note` VARCHAR(255) NULL;

-- ### insp_corrective_summaries
ALTER TABLE `insp_corrective_summaries` ADD COLUMN `escalated_cases` INT NULL;
ALTER TABLE `insp_corrective_summaries` ADD COLUMN `avg_resolution_days` DECIMAL(10,2) NULL;
ALTER TABLE `insp_corrective_summaries` ADD COLUMN `on_time_rate` DECIMAL(10,2) NULL;
ALTER TABLE `insp_corrective_summaries` ADD COLUMN `effectiveness_confirmed` INT NULL;
ALTER TABLE `insp_corrective_summaries` ADD COLUMN `effectiveness_failed` INT NULL;
ALTER TABLE `insp_corrective_summaries` ADD COLUMN `created_by` BIGINT NULL;

-- ### insp_inspector_summaries
ALTER TABLE `insp_inspector_summaries` ADD COLUMN `created_by` BIGINT NULL;

-- ### insp_item_frequency_summaries
ALTER TABLE `insp_item_frequency_summaries` ADD COLUMN `item_code` VARCHAR(255) NULL;
ALTER TABLE `insp_item_frequency_summaries` ADD COLUMN `section_id` BIGINT NULL;
ALTER TABLE `insp_item_frequency_summaries` ADD COLUMN `section_name` VARCHAR(255) NULL;
ALTER TABLE `insp_item_frequency_summaries` ADD COLUMN `total_deduction` DECIMAL(10,2) NULL;
ALTER TABLE `insp_item_frequency_summaries` ADD COLUMN `avg_deduction` DECIMAL(10,2) NULL;
ALTER TABLE `insp_item_frequency_summaries` ADD COLUMN `cumulative_percentage` DECIMAL(10,2) NULL;
ALTER TABLE `insp_item_frequency_summaries` ADD COLUMN `created_by` BIGINT NULL;

-- ### insp_projects
ALTER TABLE `insp_projects` ADD COLUMN `scoring_config_snapshot` TEXT NULL;

-- ### insp_submissions
ALTER TABLE `insp_submissions` ADD COLUMN `closed_at` DATETIME NULL;
ALTER TABLE `insp_submissions` ADD COLUMN `closed_reason` VARCHAR(255) NULL;

-- ### insp_template_sections
ALTER TABLE `insp_template_sections` ADD COLUMN `parent_section_id` BIGINT NULL;
ALTER TABLE `insp_template_sections` ADD COLUMN `scoring_config` TEXT NULL;

-- ### major_directions
ALTER TABLE `major_directions` ADD COLUMN `remarks` TEXT NULL;
ALTER TABLE `major_directions` ADD COLUMN `enrollment_target` VARCHAR(255) NULL;
ALTER TABLE `major_directions` ADD COLUMN `education_form` VARCHAR(255) NULL;
ALTER TABLE `major_directions` ADD COLUMN `certificate_names` JSON NULL COMMENT 'List<String> stored as JSON';
ALTER TABLE `major_directions` ADD COLUMN `training_standard` VARCHAR(255) NULL;
ALTER TABLE `major_directions` ADD COLUMN `cooperation_enterprise` VARCHAR(255) NULL;
ALTER TABLE `major_directions` ADD COLUMN `max_enrollment` INT NULL;

-- ### permissions
ALTER TABLE `permissions` ADD COLUMN `permission_desc` VARCHAR(255) NULL;
ALTER TABLE `permissions` ADD COLUMN `resource_type` INT NULL;
ALTER TABLE `permissions` ADD COLUMN `industry` VARCHAR(255) NULL;
ALTER TABLE `permissions` ADD COLUMN `plugin_class` VARCHAR(255) NULL;
ALTER TABLE `permissions` ADD COLUMN `origin` VARCHAR(255) NULL;

-- ### roles
ALTER TABLE `roles` ADD COLUMN `role_desc` VARCHAR(255) NULL;
ALTER TABLE `roles` ADD COLUMN `industry` VARCHAR(255) NULL;
ALTER TABLE `roles` ADD COLUMN `plugin_class` VARCHAR(255) NULL;
ALTER TABLE `roles` ADD COLUMN `origin` VARCHAR(255) NULL;

-- ### semester_course_offerings
ALTER TABLE `semester_course_offerings` ADD COLUMN `week_type` INT NULL COMMENT '0=每周 1=单周 2=双周';

-- ### semesters
ALTER TABLE `semesters` ADD COLUMN `start_year` INT NULL;
ALTER TABLE `semesters` ADD COLUMN `deleted` TINYINT(1) NOT NULL DEFAULT 0;

-- ### system_configs
ALTER TABLE `system_configs` ADD COLUMN `config_group` VARCHAR(255) NULL;
ALTER TABLE `system_configs` ADD COLUMN `config_label` VARCHAR(255) NULL;
ALTER TABLE `system_configs` ADD COLUMN `config_desc` TEXT NULL;
ALTER TABLE `system_configs` ADD COLUMN `is_system` INT NULL;
ALTER TABLE `system_configs` ADD COLUMN `sort_order` INT NULL;
ALTER TABLE `system_configs` ADD COLUMN `status` INT NULL;
ALTER TABLE `system_configs` ADD COLUMN `deleted` TINYINT(1) NOT NULL DEFAULT 0;

-- ### system_messages
ALTER TABLE `system_messages` ADD COLUMN `updated_at` DATETIME NULL;

-- ### teacher_assignments
ALTER TABLE `teacher_assignments` ADD COLUMN `role` VARCHAR(255) NULL;
ALTER TABLE `teacher_assignments` ADD COLUMN `is_current` TINYINT(1) NULL;
ALTER TABLE `teacher_assignments` ADD COLUMN `deleted` TINYINT(1) NOT NULL DEFAULT 0;

-- ### user_student
ALTER TABLE `user_student` ADD COLUMN `user_id` BIGINT NULL;
ALTER TABLE `user_student` ADD COLUMN `admission_date` DATE NULL;
ALTER TABLE `user_student` ADD COLUMN `graduation_date` DATE NULL;
ALTER TABLE `user_student` ADD COLUMN `student_status` INT NULL;
ALTER TABLE `user_student` ADD COLUMN `special_notes` TEXT NULL;

